### ISSUE TITLE
NPTT fails to close files it opens

### ISSUE THREAD

**Issue by york-stsci** [spacetelescope/nirspec_pipe_testing_tool#175]
This occurs in a number of places. To provide a few examples,

- in core_utils.py, the function get_sci_extensions on line 114 opens a FITS file but does not close it
- in cal webb_spec2_pytests
  - in auxilliary_code
    - in auxilliary_functions.py, get_sci_extensions on line 52
    - in barshadow_testing.py, run_barshadow_tests on line 39 (line 83, line 101, line 285)
    - in create_metafile.py, fix_metafile on line 214
    - in flattest_fs.py, in function flattest on line 36 (line 201)
    - in msa_flagging_testing.py in run_msa_flagging_testing on line 163, at line 191.
    - in pathloss_fs_ps_S400A1.py in get_ps_uni_extensions on line 33
    - above file, in pathtest function on line 66, at lines 168, 181, 272
    - in pathloss_fs_ps.py in get_ps_uni_extensions on line 39
    - above file in pathtest function on line 72 at lines 116, 151, 303

And additional examples in pathloss_fs_uni.py, pathloss_ifu_ps.py, pathloss_ifu_uni.py, pathloss_mos_ps.py, pathloss_mos_uni.py, crm2STpipeline.py, ESAsim_post_processing.py, move_data2ext1.py

**Comment by penaguerrero** [comment]
This issue was fixed. Thank you so much for reporting it.
